### ISSUE TITLE
Add possibility to use multiple entry points

### ISSUE THREAD

**Issue by vladshcherbin** [rollup/rollup-plugin-run#2]
Hey,

I am using this plugin with a single entry point and it works really well. Now I need to split bundle into 2 chunks, one of them has react ssr code which I want to track separately. This chunk is imported and is used in the main one and is not supposed to be executed.

Currently, the plugin gives an error for multiple entry points, however I know what chunk needs to be executed. If an object is used as an entry point with multiple keys, maybe it's possible to add an option where you can set which chunk is expected to be executed.

For example:

```js
export default {
  input: {
    app: 'src/index.js',
    ssr: 'src/ssr.js'
  },
  output: {
    file: 'dist/index.js',
    format: 'cjs'
  },
  plugins: [
    run({
      entry: 'app'
    })
  ]
};
```

What do you think?

**Comment by shellscape** [comment]
@vladshcherbin sounds like a good change to me. We're going to be moving this to the plugins monorepo soon, and at that point, that's a good time for a PR

**Comment by shellscape** [comment]
The move is done. Please head to https://github.com/rollup/plugins.
